### ISSUE TITLE
Can I use Seurat objects as the inputs?

### ISSUE THREAD

**Issue by hjp34** [Winnie09/Lamian#10]
Hi,

Thank you so much for developing the wonderful analytical tool, Lamian. I wonder if you could kindly share the new version of Lamian, in which I can use Seurat objects as the inputs. Thank you so much for your help in advance. 

June

**Comment by Winnie09** [comment]
Hi June,

I am terribly sorry for the late reply. The revision of this software has been delayed due to some issues. Now the newest version of Lamian is available on Github: https://github.com/Winnie09/Lamian.

Please feel free to let me know if you encounter any issues when using the new version. Thank you for your interest in our work.


Best regards,

Wenpin

---------------------------------------------------

Wenpin Hou, Ph.D.

Postdoctoral Fellow, Department of Biostatistics

Bloomberg School of Public Health

Johns Hopkins University

Homepage: https://winnie09.github.io/Wenpin_Hou/

________________________________
From: hjp34 ***@***.***>
Sent: Wednesday, March 16, 2022 9:46 PM
To: Winnie09/Lamian ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Winnie09/Lamian] Can I use Seurat objects as the inputs? (Issue #10)


      External Email - Use Caution



Hi,

Thank you so much for developing the wonderful analytical tool, Lamian. I wonder if you could kindly share the new version of Lamian, in which I can use Seurat objects as the inputs. Thank you so much for your help in advance.

June

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWinnie09%2FLamian%2Fissues%2F10&data=04%7C01%7Cwhou10%40jhu.edu%7C5181b1bbcf6b443b7a4008da07b7fc4d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637830784044427679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZcHCRNRshoSiA%2BWjmlEmdykfTrFt7QQgEgcrHarXuq0%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFOSWVK3PKGWCID64KLFGQTVAKFIBANCNFSM5Q5RKDBA&data=04%7C01%7Cwhou10%40jhu.edu%7C5181b1bbcf6b443b7a4008da07b7fc4d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637830784044427679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XG62tyeRNsL5oM2xufbsANi7k6h7KqVTbp3Fw81mz%2FU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cwhou10%40jhu.edu%7C5181b1bbcf6b443b7a4008da07b7fc4d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637830784044427679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IxRY%2B0Wa4g8lwZiZYEXsaPJflJpKGUsXGu417%2Bj0kIo%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cwhou10%40jhu.edu%7C5181b1bbcf6b443b7a4008da07b7fc4d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637830784044427679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vR7f3OERTkcZ44oqB8Kh6lSMJqIbT%2FZkxeTE9OncMec%3D&reserved=0>.
