### ISSUE TITLE
XDE clusters' difference

### ISSUE THREAD

**Issue by xzsword** [Winnie09/Lamian#6]
Hello,
I have one question on the gene clusters. When I tied the test data for XDE test. I set k = 5 as follows:

clusterGene(Res, gene = diffgene, type = 'variable', k=5)

However, when I check the heatmap and it shows 8 gene clusters. I do not know how to understand the difference between the k in clusterGene function and the final 8 gene clusters shown in the heatmap.

**Comment by Winnie09** [comment]
Hi,

You got 8 gene clusters because the trend differential genes were further split up. When k = 5, two clusters will be assigned to mean differential genes (one for the genes with higher expression in group 1, and the other one for the genes with higher expression in group 2); the remaining trend differential genes will first be grouped into three groups (5-2=3) according to their temporal group difference, but within each group, genes will be further split up into two according to the expression higher in group 1 or group 2, so we will get 2*3 clusters. Therefore, in total, there are 2 + 2*3 clusters shown in the heatmap. 

We will release a new version in March 2022 with more functions and it will also be more computationally efficient.  Stay in tune! Thank you.

**Comment by xzsword** [comment]
Thank you for your answer. Now I got 4 groups and want to compare the XDE at the same time. It seems that the gene clusters make me confusing. I set k.auto = T and got 5 clusters. However, the heatmap shows 13 clusters and I don't know which cluster in heatmap from which cluster by kmeans.
